language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
    - php: 7.4

before_install:
  - composer self-update

install:
  - composer update

script:
  - composer run test